// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { MoveSteve } from "./move_steve_reducer.ts";
export { MoveSteve };
import { MoveSteveDirection } from "./move_steve_direction_reducer.ts";
export { MoveSteveDirection };
import { SetName } from "./set_name_reducer.ts";
export { SetName };
import { SpawnSteve } from "./spawn_steve_reducer.ts";
export { SpawnSteve };
import { Tick } from "./tick_reducer.ts";
export { Tick };

// Import and reexport all table handle types
import { FoodTableHandle } from "./food_table.ts";
export { FoodTableHandle };
import { SteveTableHandle } from "./steve_table.ts";
export { SteveTableHandle };
import { TickScheduleTableHandle } from "./tick_schedule_table.ts";
export { TickScheduleTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };

// Import and reexport all types
import { Food } from "./food_type.ts";
export { Food };
import { Position } from "./position_type.ts";
export { Position };
import { Steve } from "./steve_type.ts";
export { Steve };
import { TickSchedule } from "./tick_schedule_type.ts";
export { TickSchedule };
import { User } from "./user_type.ts";
export { User };

const REMOTE_MODULE = {
  tables: {
    food: {
      tableName: "food",
      rowType: Food.getTypeScriptAlgebraicType(),
      primaryKey: "position",
    },
    steve: {
      tableName: "steve",
      rowType: Steve.getTypeScriptAlgebraicType(),
      primaryKey: "user",
    },
    tick_schedule: {
      tableName: "tick_schedule",
      rowType: TickSchedule.getTypeScriptAlgebraicType(),
      primaryKey: "scheduledId",
    },
    user: {
      tableName: "user",
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
    },
  },
  reducers: {
    client_connected: {
      reducerName: "client_connected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    move_steve: {
      reducerName: "move_steve",
      argsType: MoveSteve.getTypeScriptAlgebraicType(),
    },
    move_steve_direction: {
      reducerName: "move_steve_direction",
      argsType: MoveSteveDirection.getTypeScriptAlgebraicType(),
    },
    set_name: {
      reducerName: "set_name",
      argsType: SetName.getTypeScriptAlgebraicType(),
    },
    spawn_steve: {
      reducerName: "spawn_steve",
      argsType: SpawnSteve.getTypeScriptAlgebraicType(),
    },
    tick: {
      reducerName: "tick",
      argsType: Tick.getTypeScriptAlgebraicType(),
    },
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "ClientConnected", args: ClientConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "MoveSteve", args: MoveSteve }
| { name: "MoveSteveDirection", args: MoveSteveDirection }
| { name: "SetName", args: SetName }
| { name: "SpawnSteve", args: SpawnSteve }
| { name: "Tick", args: Tick }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_connected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  moveSteve(x: number, y: number) {
    const __args = { x, y };
    let __writer = new BinaryWriter(1024);
    MoveSteve.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("move_steve", __argsBuffer, this.setCallReducerFlags.moveSteveFlags);
  }

  onMoveSteve(callback: (ctx: ReducerEventContext, x: number, y: number) => void) {
    this.connection.onReducer("move_steve", callback);
  }

  removeOnMoveSteve(callback: (ctx: ReducerEventContext, x: number, y: number) => void) {
    this.connection.offReducer("move_steve", callback);
  }

  moveSteveDirection(dx: number, dy: number) {
    const __args = { dx, dy };
    let __writer = new BinaryWriter(1024);
    MoveSteveDirection.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("move_steve_direction", __argsBuffer, this.setCallReducerFlags.moveSteveDirectionFlags);
  }

  onMoveSteveDirection(callback: (ctx: ReducerEventContext, dx: number, dy: number) => void) {
    this.connection.onReducer("move_steve_direction", callback);
  }

  removeOnMoveSteveDirection(callback: (ctx: ReducerEventContext, dx: number, dy: number) => void) {
    this.connection.offReducer("move_steve_direction", callback);
  }

  setName(name: string) {
    const __args = { name };
    let __writer = new BinaryWriter(1024);
    SetName.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_name", __argsBuffer, this.setCallReducerFlags.setNameFlags);
  }

  onSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("set_name", callback);
  }

  removeOnSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("set_name", callback);
  }

  spawnSteve(x: number, y: number) {
    const __args = { x, y };
    let __writer = new BinaryWriter(1024);
    SpawnSteve.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("spawn_steve", __argsBuffer, this.setCallReducerFlags.spawnSteveFlags);
  }

  onSpawnSteve(callback: (ctx: ReducerEventContext, x: number, y: number) => void) {
    this.connection.onReducer("spawn_steve", callback);
  }

  removeOnSpawnSteve(callback: (ctx: ReducerEventContext, x: number, y: number) => void) {
    this.connection.offReducer("spawn_steve", callback);
  }

  tick(arg: TickSchedule) {
    const __args = { arg };
    let __writer = new BinaryWriter(1024);
    Tick.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("tick", __argsBuffer, this.setCallReducerFlags.tickFlags);
  }

  onTick(callback: (ctx: ReducerEventContext, arg: TickSchedule) => void) {
    this.connection.onReducer("tick", callback);
  }

  removeOnTick(callback: (ctx: ReducerEventContext, arg: TickSchedule) => void) {
    this.connection.offReducer("tick", callback);
  }

}

export class SetReducerFlags {
  moveSteveFlags: CallReducerFlags = 'FullUpdate';
  moveSteve(flags: CallReducerFlags) {
    this.moveSteveFlags = flags;
  }

  moveSteveDirectionFlags: CallReducerFlags = 'FullUpdate';
  moveSteveDirection(flags: CallReducerFlags) {
    this.moveSteveDirectionFlags = flags;
  }

  setNameFlags: CallReducerFlags = 'FullUpdate';
  setName(flags: CallReducerFlags) {
    this.setNameFlags = flags;
  }

  spawnSteveFlags: CallReducerFlags = 'FullUpdate';
  spawnSteve(flags: CallReducerFlags) {
    this.spawnSteveFlags = flags;
  }

  tickFlags: CallReducerFlags = 'FullUpdate';
  tick(flags: CallReducerFlags) {
    this.tickFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get food(): FoodTableHandle {
    return new FoodTableHandle(this.connection.clientCache.getOrCreateTable<Food>(REMOTE_MODULE.tables.food));
  }

  get steve(): SteveTableHandle {
    return new SteveTableHandle(this.connection.clientCache.getOrCreateTable<Steve>(REMOTE_MODULE.tables.steve));
  }

  get tickSchedule(): TickScheduleTableHandle {
    return new TickScheduleTableHandle(this.connection.clientCache.getOrCreateTable<TickSchedule>(REMOTE_MODULE.tables.tick_schedule));
  }

  get user(): UserTableHandle {
    return new UserTableHandle(this.connection.clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
